catalog:
  '@iconify-json/ooui': ^1.2.21
  '@iconify-json/ri': ^1.2.10
  '@iconify-json/simple-icons': ^1.2.93
  '@sxzz/eslint-config': ^8.5.0
  '@sxzz/prettier-config': ^2.3.2
  '@types/fontkit': ^2.0.9
  '@types/node': ^26.2.0
  '@unocss/eslint-plugin': ^66.8.0
  '@unocss/nuxt': ^66.8.0
  '@unocss/reset': ^66.8.0
  '@vueuse/core': ^14.4.0
  '@vueuse/nuxt': ^14.4.0
  '@vueuse/router': ^14.4.0
  eslint: ^10.8.1
  fflate: ^0.8.3
  fontkit: ^2.0.4
  nuxt: ^4.5.2
  prettier: ^3.9.6
  subset-font: ^2.5.0
  typescript: ~6.0.3
  unocss: ^66.8.0
  vitest: ^4.1.11
  vue: ^3.5.41
  vue-tsc: ^3.3.10
  wrangler: 4.124.0
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAge: 0
