import { zhCN } from './zh-cn.ts'

/**
 * The language never enters the URL: one prerendered build, locale decided on
 * the client. The cost is that other languages get no URL of their own, are
 * not indexed, and cannot be linked to -- hence no hreflang either. Switching
 * to locale-prefixed routes means changing this file and useT, nothing else.
 */
export const LOCALES = ['zh-CN', 'zh-TW', 'zh-HK', 'ja-JP', 'ko-KR'] as const
export type Locale = (typeof LOCALES)[number]

/** What the prerendered HTML carries, and what anything unmatched falls back to. */
export const DEFAULT_LOCALE: Locale = 'zh-CN'

export type Messages = typeof zhCN

export interface LocaleMeta {
  /** <html lang> */
  htmlLang: string
  /**
   * Interface body type. A page about glyph differences must not itself use
   * the wrong glyphs, so the body font follows the interface language.
   * The five table columns stay pinned to their own regions regardless.
   */
  sans: string
  /**
   * Base name of the self-hosted subsets of the interface copy, generated by
   * scripts/build-fonts.ts as `<uiFamily> Sans` and `<uiFamily> Serif`. They
   * sit ahead of the Google families so those are only ever consulted for a
   * character the subset missed.
   */
  uiFamily: string
}

export const LOCALE_META: Record<Locale, LocaleMeta> = {
  'zh-CN': {
    htmlLang: 'zh-CN',
    sans: "'Noto Sans SC'",
    uiFamily: 'UI zh-CN',
  },
  'zh-TW': {
    htmlLang: 'zh-TW',
    sans: "'Noto Sans TC'",
    uiFamily: 'UI zh-TW',
  },
  'zh-HK': {
    htmlLang: 'zh-HK',
    sans: "'Noto Sans HK'",
    uiFamily: 'UI zh-HK',
  },
  'ja-JP': {
    htmlLang: 'ja-JP',
    sans: "'Noto Sans JP'",
    uiFamily: 'UI ja-JP',
  },
  'ko-KR': {
    htmlLang: 'ko-KR',
    sans: "'Noto Sans KR'",
    uiFamily: 'UI ko-KR',
  },
}

/**
 * Each language named in its own words, so a reader can find theirs whatever
 * the interface is currently set to. The names come from the platform rather
 * than a hand-kept list -- CLDR already knows what to call these.
 */
export const localeName = (code: Locale): string =>
  new Intl.DisplayNames([code], { type: 'language' }).of(code) ?? code

/**
 * Only the default is bundled with the app. The others arrive as their own
 * chunk the first time someone asks for them, so a reader never downloads a
 * language they do not read.
 */
export const LOADERS: Record<Locale, () => Promise<Messages>> = {
  'zh-CN': () => Promise.resolve(zhCN),
  'zh-TW': async () => (await import('./zh-tw.ts')).zhTW,
  'zh-HK': async () => (await import('./zh-hk.ts')).zhHK,
  'ja-JP': async () => (await import('./ja-jp.ts')).jaJP,
  'ko-KR': async () => (await import('./ko-kr.ts')).koKR,
}

/**
 * The best locale for a browser's language list, in the browser's own order of
 * preference. Japanese and Korean tags take their respective copy. A Chinese
 * tag naming Hong Kong or Macao takes the Hong Kong copy, one naming Taiwan or
 * the traditional script takes the Taiwanese copy, and any other Chinese tag
 * takes the simplified. Anything else leaves it undecided, so the caller can
 * fall back.
 */
export function matchLocale(tags: readonly string[]): Locale | undefined {
  for (const tag of tags) {
    const lower = tag.toLowerCase()
    const language = lower.split('-', 1)[0]
    if (language === 'ja') return 'ja-JP'
    if (language === 'ko') return 'ko-KR'
    if (language !== 'zh') continue
    const parts = new Set(lower.split('-'))
    if (parts.has('hk') || parts.has('mo')) return 'zh-HK'
    if (parts.has('tw') || parts.has('hant')) return 'zh-TW'
    return 'zh-CN'
  }
  return undefined
}
